from . import test_address_format
from . import test_ingestion_dedup
from . import test_query_normalize
from . import test_clearing_ux
from . import test_security
from . import test_autocomplete_chain
from . import test_address_fields
from . import test_address_sync
from . import test_address_ownership
from . import test_translit
from . import test_translit_consistency
from . import test_old_names_reset
from . import test_details_refresh
from . import test_perf_settings
from . import test_user_agent
